/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * supporter object
 * @export
 * @interface GetKillmailsKillmailIdKillmailHashSupporter
 */
export interface GetKillmailsKillmailIdKillmailHashSupporter {
    /**
     * alliance_id integer
     * @type {number}
     * @memberof GetKillmailsKillmailIdKillmailHashSupporter
     */
    allianceId?: number;
    /**
     * character_id integer
     * @type {number}
     * @memberof GetKillmailsKillmailIdKillmailHashSupporter
     */
    characterId?: number;
    /**
     * corporation_id integer
     * @type {number}
     * @memberof GetKillmailsKillmailIdKillmailHashSupporter
     */
    corporationId?: number;
    /**
     * faction_id integer
     * @type {number}
     * @memberof GetKillmailsKillmailIdKillmailHashSupporter
     */
    factionId?: number;
    /**
     * Obsolete attribute
     * 
     * @type {boolean}
     * @memberof GetKillmailsKillmailIdKillmailHashSupporter
     */
    isRegen: boolean;
    /**
     * The amount the supporter actually supporter toward the victim
     * 
     * @type {number}
     * @memberof GetKillmailsKillmailIdKillmailHashSupporter
     */
    repairDone: number;
    /**
     * The type the supporter used toward the victim
     * 
     * @type {number}
     * @memberof GetKillmailsKillmailIdKillmailHashSupporter
     */
    repairerTypeId?: number;
    /**
     * Security status for the supporter
     * 
     * @type {number}
     * @memberof GetKillmailsKillmailIdKillmailHashSupporter
     */
    securityStatus?: number;
    /**
     * What ship was the supporter flying
     * 
     * @type {number}
     * @memberof GetKillmailsKillmailIdKillmailHashSupporter
     */
    shipTypeId?: number;
}

/**
 * Check if a given object implements the GetKillmailsKillmailIdKillmailHashSupporter interface.
 */
export function instanceOfGetKillmailsKillmailIdKillmailHashSupporter(value: object): value is GetKillmailsKillmailIdKillmailHashSupporter {
    if (!('isRegen' in value) || value['isRegen'] === undefined) return false;
    if (!('repairDone' in value) || value['repairDone'] === undefined) return false;
    return true;
}

export function GetKillmailsKillmailIdKillmailHashSupporterFromJSON(json: any): GetKillmailsKillmailIdKillmailHashSupporter {
    return GetKillmailsKillmailIdKillmailHashSupporterFromJSONTyped(json, false);
}

export function GetKillmailsKillmailIdKillmailHashSupporterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetKillmailsKillmailIdKillmailHashSupporter {
    if (json == null) {
        return json;
    }
    return {
        
        'allianceId': json['alliance_id'] == null ? undefined : json['alliance_id'],
        'characterId': json['character_id'] == null ? undefined : json['character_id'],
        'corporationId': json['corporation_id'] == null ? undefined : json['corporation_id'],
        'factionId': json['faction_id'] == null ? undefined : json['faction_id'],
        'isRegen': json['is_regen'],
        'repairDone': json['repair_done'],
        'repairerTypeId': json['repairer_type_id'] == null ? undefined : json['repairer_type_id'],
        'securityStatus': json['security_status'] == null ? undefined : json['security_status'],
        'shipTypeId': json['ship_type_id'] == null ? undefined : json['ship_type_id'],
    };
}

export function GetKillmailsKillmailIdKillmailHashSupporterToJSON(json: any): GetKillmailsKillmailIdKillmailHashSupporter {
    return GetKillmailsKillmailIdKillmailHashSupporterToJSONTyped(json, false);
}

export function GetKillmailsKillmailIdKillmailHashSupporterToJSONTyped(value?: GetKillmailsKillmailIdKillmailHashSupporter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alliance_id': value['allianceId'],
        'character_id': value['characterId'],
        'corporation_id': value['corporationId'],
        'faction_id': value['factionId'],
        'is_regen': value['isRegen'],
        'repair_done': value['repairDone'],
        'repairer_type_id': value['repairerTypeId'],
        'security_status': value['securityStatus'],
        'ship_type_id': value['shipTypeId'],
    };
}

